@startuml

!theme toy
top to bottom direction
skinparam linetype ortho

class ApplicationMain {
   + Map map
  + ApplicationMain(): 
  + main(String[]): void
}
class Champion {
  - level: int
  - sword: boolean
  - shield: boolean
  - maxHp: int
  - regeneration: boolean
  - type: String
  - strength: int
  - move: boolean
  - luck: int
  - y_index: int
  - level: int
  - range: int
  - hp: int
  - x_index: int
}
class Chest {
  + Chest(String, int, int): 
  + whatsInside(): boolean
   mimicGenerate: boolean
}
interface DefaultRequired << interface >> {
  newIndex(int, int): void
   setMove(boolean value)
   newIndex(int newY, int newX)
   getX_index(): int
   getY_index(): int
   getHp(): int
   getMaxHp(): int
   getLvl(): int
   getStrength(): int
   getRange(): int
    getType(): String
    getLuck(): int
    getLevel(): int
    getMove(): boolean
    getSword(): boolean
    getShield(): boolean
    getRegeneration(): boolean

}
class Elf {
  - level: 1
   - sword: true
   - shield: true
   - maxHp: 20
    - regeneration: false
    - type: champion
    - strength: 5
    - move: true
    - luck: 5
    - y_index: 5
    - level: 5
    - range: 5
    - hp: 20
    - x_index: 7
}
class Human {
  - level: 1
   - sword: true
   - shield: true
   - maxHp: 20
    - regeneration: false
    - type: champion
    - strength: 5
    - move: true
    - luck: 5
    - y_index: 5
    - level: 5
    - range: 5
    - hp: 20
    - x_index: 7
}
interface Interaction << interface >> {
   kill(String): String
   boost(): String
   trap(): String
   pickUp(): String
}
class Item {
  + Item(String, int, int): 
}
class Kit {
  + Kit(String, int, int): 
}
class Map {
  - width: 24
  - map: ArrayList<ArrayList<Champion>>
  - height: 16
  + Human human1
  + Ork ork1
  + Elf elf1
}
class Ork {
  - level: 1
   - sword: true
   - shield: true
   - maxHp: 20
    - regeneration: false
    - type: champion
    - strength: 5
    - move: true
    - luck: 5
    - y_index: 5
    - level: 5
    - range: 5
    - hp: 20
    - x_index: 7
}
class Potion {
  + Potion(String, int, int): 
}
class SuperStart {
  + SuperStart(): 
  + main(String[]): void
}

Map         -[#000000,dotted]-^  ApplicationMain
Elf              -[#000000,dotted]-^  Map
Ork              -[#000000,dotted]-^  Map
Human            -[#000000,dotted]-^  Map
ApplicationMain            -[#000000,dotted]-^  SuperStart


Champion         -[#008200,dashed]-^  DefaultRequired 
Chest            -[#000082,plain]-^  Kit             
Elf              -[#000082,plain]-^  Champion        
Human            -[#000082,plain]-^  Champion        
Item             -[#000082,plain]-^  Kit             
Kit              -[#000082,plain]-^  Champion        
Ork              -[#000082,plain]-^  Champion        
Ork              -[#008200,dashed]-^  Interaction     
Potion           -[#000082,plain]-^  Kit             
@enduml
